### ISSUE TITLE
link to this project from Esri/arcgis-to-geojson-utils README?

### ISSUE THREAD

**Issue by jgravois** [chris48s/arcgis2geojson#5]
greetings! :wave:

if you're interested in advertising this port, i'd be happy to merge a PR for that.

**Comment by chris48s** [comment]
Thanks :+1: Happy for you to link to this project if you want. I'll leave it with you to decide on the words you want to use around that.

**Comment by jgravois** [comment]
:tada: [`ed3c56b`](https://github.com/Esri/arcgis-to-geojson-utils/blob/ed3c56bd99acf73d454f3d6d09aba00bad373ce4/README.md#ports)
