### ISSUE TITLE
CLI fails to convert this file - is that expected behaviour?

### ISSUE THREAD

**Issue by AlisterH** [chris48s/arcgis2geojson#7]
The attached file comes out of an .mpk
I thought I should be able to convert it using the arcgis2geojson CLI.
It does not work - is this a problem with arcgis2geojson, or did I just think wrong?  Maybe this file isn't actually a (valid? complete?) esrijson... in which case I figure it is worth posting this just to document it for anyone else who tries the same thing.
[webmap.json.txt](https://github.com/chris48s/arcgis2geojson/files/4346462/webmap.json.txt)

**Comment by chris48s** [comment]
I've not seen one of these before, but broadly:

It is expected that this whole file won't convert as-is, but it does contain a bunch of layers that will each convert individually. You should be able to convert the whole thing to multiple geojson files by iterating over the layers and converting each layers to geojson.

For example:

```py
from arcgis2geojson import arcgis2geojson
import json


j = json.load("webmap.json.txt")

arcgis2geojson(
    j['operationalLayers'][0]['featureCollection']['layers'][0]['featureSet']
)
```

Hope that helps.

**Comment by AlisterH** [comment]
OK thanks.
For the record I can just convert it to a single file like this:
```#!/usr/bin/env python3
from arcgis2geojson import arcgis2geojson
import json, sys, pprint

if len(sys.argv) < 2:
    print("Usage: mpkjson2geojson.py source_file")
    sys.exit(1)

input = sys.argv[1]

f = open(input)
j = json.load(f)

output = arcgis2geojson(
    j['operationalLayers'][0]['featureCollection']['layers'][0]['featureSet']
)

pp = pprint.PrettyPrinter(indent=4)
pp.pprint(output)
```
The result apparently isn't valid - apart from changing single to double quotes I need to tidy up the properties of each feature i.e.
- change the value of the "measureEnabled" property from a capitalised `True `to simply `true` (I guess the capital T has a similar cause to the single quotes).
- remove the measureValue and styles properties, or change their values into a single string.

And since all the features are in the same ("alternate") crs I can add this to the feature collection to specify it: `"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::2193" } }`

**Comment by chris48s** [comment]
> For the record I can just convert it to a single file

Bear in mind with the snippet I posted, I just hard-coded the indexes to 0 so that code only converts the first layer. You would need to loop over `operationalLayers` and `layers` to extract all the information from your file.

> apart from changing single to double quotes I need to tidy up

When using as a library,

* If you pass in a json string, `arcgis2geojson()` will return a json string
* if you pass in a python dictionary, `arcgis2geojson()` will return a python dictionary

The example I gave passes in a python dict. You can either:

```py
out = arcgis2geojson(
    json.dumps(j['operationalLayers'][0]['featureCollection']['layers'][0]['featureSet'])
)
print(out)
```

or

```py
out = arcgis2geojson(
    j['operationalLayers'][0]['featureCollection']['layers'][0]['featureSet']
)
print(json.dumps(out))
```

**Comment by chris48s** [comment]
Closing this as resolved. I've made some changes to the README examples off the back of this conversation.
